[package]
name = "stackarr-cardigann"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
scraper = "0.22"
indexmap = { workspace = true, features = ["serde"] }

reqwest = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }

tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
