[package]
name = "stackarr-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
embed-ui = ["rust-embed"]

[dependencies]
stackarr-core = { workspace = true }
stackarr-media = { workspace = true }
stackarr-parser = { workspace = true }
stackarr-quality = { workspace = true }
stackarr-indexer = { workspace = true }
stackarr-download = { workspace = true }
stackarr-import = { workspace = true }
stackarr-scheduler = { workspace = true }
stackarr-notify = { workspace = true }
stackarr-metadata = { workspace = true }
stackarr-migrate = { workspace = true }
stackarr-plex = { workspace = true }
stackarr-cardigann = { workspace = true }
stackarr-stream = { workspace = true }
serde_yaml = { workspace = true }
axum = { workspace = true, features = ["multipart"] }
tower = { workspace = true }
tower-http = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
utoipa-swagger-ui = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
arc-swap = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
bytes = { workspace = true }
tempfile = "3"
librtbit = { workspace = true }
nzb-web = { workspace = true }
nzbdav-core = { workspace = true }
nzbdav-dav = { workspace = true }
nzbdav-stream = { workspace = true }
nzbdav-pipeline = { workspace = true }
reqwest = { workspace = true }
bincode = { workspace = true }
flate2 = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
serde_urlencoded = { workspace = true }
urlencoding = { workspace = true }
governor = { workspace = true }
dashmap = { workspace = true }
base64 = { workspace = true }
rust-embed = { version = "8", optional = true }
mime_guess = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
tokio-rustls = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }

[dev-dependencies]
stackarr-core = { workspace = true, features = ["testing"] }
http-body-util = { workspace = true }
uuid = { workspace = true }
