services:
  mariadb:
    image: mariadb:11.4
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MARIADB_ROOT_PASSWORD=stackarr
      - MARIADB_USER=stackarr
      - MARIADB_PASSWORD=stackarr
      - MARIADB_DATABASE=stackarr
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mariadbdata:
