services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=stackarr
      - POSTGRES_PASSWORD=stackarr
      - POSTGRES_DB=stackarr

volumes:
  pgdata:
